name: Automatic Merge Pull Request
on: pull_request_target

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: tspascoal/get-user-teams-membership@v2
        id: actorTeams
        with:
          username: ${{ github.event.pull_request.user.login }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            eq1:
              - 'src/abstraction/eq1*/**'
            eq2:
              - 'src/abstraction/eq2*/**'
            eq3:
              - 'src/abstraction/eq3*/**'
            eq4:
              - 'src/abstraction/eq4*/**'
            eq5:
              - 'src/abstraction/eq5*/**'
            eq6:
              - 'src/abstraction/eq6*/**'
            eq7:
              - 'src/abstraction/eq7*/**'
            eq8:
              - 'src/abstraction/eq8*/**'
            eq9:
              - 'src/abstraction/eq9*/**'
            eqX:
              - 'src/abstraction/eqX*/**'
            root:
              - '*'
              - '.github/**'
              - '.settings/**'
              - 'docs/**'
              - 'lib/**'
              - 'src/controle/**'
              - 'src/presentation/**'
              - 'test/**'
              
      - name: Check files
        run: |
          eq1=${{ steps.filter.outputs.eq1 }}
          eq2=${{ steps.filter.outputs.eq2 }}
          eq3=${{ steps.filter.outputs.eq3 }}
          eq4=${{ steps.filter.outputs.eq4 }}
          eq5=${{ steps.filter.outputs.eq5 }}
          eq6=${{ steps.filter.outputs.eq6 }}
          eq7=${{ steps.filter.outputs.eq7 }}
          eq8=${{ steps.filter.outputs.eq8 }}
          eq9=${{ steps.filter.outputs.eq9 }}
          eqX=${{ steps.filter.outputs.eqX }}
          root=${{ steps.filter.outputs.root }}

          sum=$((eq1 + eq2 + eq3 + eq4 + eq5 + eq6 + eq7 + eq8 + eq9 + eqX + root))

          echo $sum

          if [[ $sum -ne 1 ]]; then
            echo "The pull request involves several teams. Exiting the workflow."
            exit 0
          fi

      - name: Enable auto-merge
        if: failure() && contains(github.event.pull_request.changed_files, steps.actorTeams.outputs.teams[0])
        run: gh pr merge --auto --merge ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
